### ISSUE TITLE
Qubes template update fails with tb-updater

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [Whonix/tb-updater#13] opened 2021-04-26 09:31 UTC
Using Qubes Updater or terminal in debian-10 template, for several days:

```
...
Do you want to continue? [Y/n] y
Setting up tb-updater (3:19.3-1) ...
/etc/torbrowser.d/50_user.conf: line 3: syntax error near unexpected token `“extensions.torbutton.startup”,'
/etc/torbrowser.d/50_user.conf: line 3: `user_pref(“extensions.torbutton.startup”, false)'
###########################################################
## update-torbrowser script bug.
## No panic. Nothing is broken. Just some rare condition
## has been hit. Try again later. There is likely a
## solution for this problem. Please see the Whonix News,
## Whonix User Help Forum and Whonix Documentation.
## https://www.whonix.org/wiki/
## Please report this bug!
##
## BASH_COMMAND: bash -n "$i"
## exit_code: 2
##
## output: 
## output_opts: 
## progressbaridx: 
##
## Experts only:
## bash -x update-torbrowser
###########################################################

####################################################################
## BEGIN ERROR in /var/lib/dpkg/info/tb-updater.postinst detected!
##
## ERROR LOG:
## See above.
##
## BASH_COMMAND: $tool $chroot_maybe --postinst
## EXIT_CODE: 1
##
## END ERROR in /var/lib/dpkg/info/tb-updater.postinst detected!
## Please report this bug!
####################################################################

dpkg: error processing package tb-updater (--configure):
 installed tb-updater package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 tb-updater
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by adrelanos** [comment] 2021-04-26 09:34
Nothing wrong with the package most likely. This package doesn't ship file `/etc/torbrowser.d/50_user.conf`.

> /etc/torbrowser.d/50_user.conf: line 3: syntax error near unexpected token `“extensions.torbutton.startup”,'
> /etc/torbrowser.d/50_user.conf: line 3: `user_pref(“extensions.torbutton.startup”, false)'

Local configuration issue. `/etc/torbrowser.d/50_user.conf` is a user configured file.

**Comment by Ark-of-the-copepod** [comment] 2021-04-26 09:48
I see. I modified that file trying - and failing - to put a configuration to have torbrowser launch without Tor. I can't figure out where to do this - I think the tb-updater installation uses a different file structure?

Please put me out of my misery - where do I put that conf?

(I tried this:)
```
## stop torbrowser connecting to Tor. Secbrowser instructions from https://forums.whonix.org/t/tor-browser-10-without-tor/10313/4.

user_pref(“extensions.torbutton.startup”, false)
user_pref(“extensions.torlauncher.start_tor”, false)
user_pref(“network.proxy.socks_remote_dns”, false)

## and the 10.x fix

user_pref("network.dns.disabled", false)
```

**Comment by adrelanos** [comment] 2021-04-26 10:27
Firefox configuration `user_pref` cannot directly be used inside `/etc/torbrowser.d/` (`source`ed by `bash`).

indirectly: could be automated through `bash` scripting.

`bash` scripting isn't a magic bullet or different method. You need to know first how to do it manually before it can be automated using `bash`. Details on that are out of scope for support.

> I think the tb-updater installation uses a different file structure?

No. By design modifications are minimal.

https://www.whonix.org/wiki/Tor_Browser#Whonix_.E2.84.A2_Tor_Browser_Differences

Where is it located (just now written):

* https://www.whonix.org/wiki/Tor_Browser/Advanced_Users#File_Locations
* https://www.whonix.org/wiki/Tor_Browser/Advanced_Users#user.js

Otherwise for Tor Browser / Firefox modifications, https://www.whonix.org/wiki/Free_Support_Principle applies.

You could post a feature request to install a custom `user.js` file in forums.whonix.org.

**Closed by adrelanos** 2021-04-26 10:27 UTC
